### ISSUE TITLE
The annotations are not actually saved ( written to the pdf file ) . 

### ISSUE THREAD

**Issue by BharatJagtap** [lazyprogram/LazyPDFKit#1]
I tried the code . The code does draw the annotations on the view but they are not actually saved to the pdf file .

**Comment by lazyprogram** [comment]
This feature is currently under development. I will try to complete this asap. Please check back again later.

**Comment by lazyprogram** [comment]
Fixed

**Comment by lazyprogram** [comment]
Fixed. Tap 'Flatten PDF' to save annotation inside PDF.
