### ISSUE TITLE
Crash on Xcode 5 with ios 6 

### ISSUE THREAD

**Issue by Dharanics** [lazyprogram/LazyPDFKit#5]
dyld: Library not loaded: @rpath/LazyPDFKit.framework/LazyPDFKit
  Referenced from: /Users/xxxx/Library/Application Support/iPhone Simulator/6.1/Applications/sdsde545454545fgfgfg/LazyPDFKitDemo.app/LazyPDFKitDemo
  Reason: image not found

**Comment by lazyprogram** [comment]
Select Project Target -> General -> Embedded Binaries -> Add LazyPDFKit.framework.

**Comment by Dharanics** [comment]
![screen shot 2015-03-17 at 10 28 55 am](https://cloud.githubusercontent.com/assets/6879553/6680297/369df08e-cc90-11e4-9fb7-f6842f524e55.png)

**Comment by lazyprogram** [comment]
Sorry we support from xcode 6 and above. Please find the screenshot of xcode 6
![error1](https://cloud.githubusercontent.com/assets/11037540/6680432/2fa17092-cc92-11e4-99b7-de098f63c357.png)

**Comment by Dharanics** [comment]
Thank you.
