### ISSUE TITLE
Library not loaded @rpath/LazyPDFKit.framework/LazyPDFKit

### ISSUE THREAD

**Issue by karthikeyanchenniappan** [lazyprogram/LazyPDFKit#6]
I have tried  LazyKitPDF framework demo app , i am getting the below error message 

dyld: Library not loaded: @rpath/LazyPDFKit.framework/LazyPDFKit
Referenced from: /Users/Karthi-mac/Library/Developer/CoreSimulator/Devices/B086D443-2D7E-480B-8D3F-5D18A8626D94/data/Containers/Bundle/Application/63083D2D-4514-495A-8222-DB839626CD0C/testpoc.app/testpoc
Reason: image not found
I tried on remove and add framework folder in source directory and also in build phase.
I also checked on framework search path in build setting but i am getting the same issue.
I cleared derived data,run clean project in build phase nothing helps to me resolve the issue.  
Please help me to fix the issue.

**Comment by lazyprogram** [comment]
this issue is related to #5 . Please find the solution here #5

**Comment by karthikeyanchenniappan** [comment]
issues fixed thanks.
