### ISSUE TITLE
Not running on device

### ISSUE THREAD

**Issue by brunojasgv** [lazyprogram/LazyPDFKit#7]
Excellent library, runs great on simulator but it does not run on device, the error: 

ld: warning: ignoring file /Users/brunovasconcelos/Documents/LazyPDFKit/LazyPDFKit.framework/LazyPDFKit, missing required architecture arm64 in file /Users/brunovasconcelos/Documents/LazyPDFKit/LazyPDFKit.framework/LazyPDFKit (2 slices)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_LazyPDFViewController", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_LazyPDFDocument", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by oleumobi** [comment]
I am having the same problem. 
Appears that this library works fine on i386 (Simulators), but not on the actual devices which are arm64, armv7 etc.

**Comment by brunojasgv** [comment]
If "lazy program" does not have the time to maintain this project he/she could upload the source code so that we could provide some updates. Its a total waste to abandon such a nice project like this.

**Comment by lazyprogram** [comment]
Guys, currently working on this issue. Will update once I am done. Thanks for your feedback.

**Comment by lazyprogram** [comment]
Fixed.
